config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}

  root 'home#index'
  
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'  
  end

  scope '/users' do 
    resources :lesson_plans
  end 
  
  resources :books, except: [:destroy]
  resources :subjects, only: [:index, :new, :create]
  resources :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :lesson_plans
  has_many :subjects, through: :lesson_plans
  validates :title, :author, :publisher, presence: true
  validates :title, uniqueness: true
  validates :pages, presence: true, numericality: { greater_than_or_equal_to: 1 }
  accepts_nested_attributes_for :subjects

  scope :alphabet, -> { order(title: :asc) }

  def self.search(search)
    if search
      @books = Book.where('title LIKE ?', "%#{search}%")
    else 
      @books = Book.all
    end 
  end 
end

app/models/lesson_plan.rb
class LessonPlan < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :books
  validates :duration, presence: true, inclusion: { in: (1..30), message: "cannot be less than 1 day or more than 30 days." }
  validates :name, :start_date, presence: true, uniqueness: true
  validates :start_date,
  date: { after: Proc.new { Date.today }, message: 'must be after today' },
  on: :create
  accepts_nested_attributes_for :subject, reject_if: :all_blank

  scope :dates, -> { order(start_date: :asc) }
  
  def lesson_start
    start_date.strftime("%B %d, %Y")
  end 
end

app/models/search.rb
class Search
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lesson_plans
  has_many :books, through: :lesson_plans
  validates :sub_name, uniqueness: true 

  scope :creation, -> { order('created_at DESC') } 
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :lesson_plans
  validates :name, presence: true, format: { with: /[a-zA-Z]/, message: "Your name cannot contain numbers or symbols." }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :grade)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :grade)}
  end
end

app/controllers/books_controller.rb
  class BooksController < ApplicationController
    before_action :set_book, except: [:index, :new, :create]

    def index 
      @books = Book.search(params[:search]).alphabet
    end

    def new 
      @book = Book.new
      @book.subjects.build
    end 

    def create 
      @book = Book.create(book_params)
      if @book
        redirect_to @book
      else 
        render :new 
      end 
    end 

    def show
    end 

    def edit
    end 

    def update
      if @book.update(book_params) 
        redirect_to @book
      else 
        render :edit
      end 
    end 

    private

    def book_params
      params.require(:book).permit(:title, 
      :author, 
      :publisher,
      :pages)
    end  
    
    def set_book 
      @book = Book.find_by(id: params[:id])
    end 

  end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 
  def github 
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end 
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
end 

app/controllers/lesson_plans_controller.rb
  class LessonPlansController < ApplicationController
    before_action :set_lesson_plan, except: [:index, :new, :create]

    def index 
      @lesson_plans = LessonPlan.all.dates
    end  
  
    def new 
      @lesson_plan = LessonPlan.new
      @lesson_plan.books.build
      @subject = Subject.new
    end 

    def create 
      @lesson_plan = current_user.lesson_plans.build(lesson_plan_params)
      if @lesson_plan.save
        redirect
      else 
        render :new
      end 
    end 

    def show
    end

    def edit 
    end 

    def update
      @lesson_plan.update(lesson_plan_params)
      if @lesson_plan.save 
        redirect
      else 
        render :edit
      end 
    end 

    def destroy
      @lesson_plan.destroy
      redirect_to lesson_plans_path
    end 

    private 

    def lesson_plan_params
      params.require(:lesson_plan).permit(:name, 
      :start_date,
      :duration, 
      :user_id,
      :subject_id,
      :subject_attributes => [:sub_name],
      :book_ids => [],
      :books_attributes => [:title, :author]
      )
    end 

    def set_lesson_plan
      @lesson_plan = LessonPlan.find_by(id: params[:id])
    end 

    def redirect 
      redirect_to lesson_plan_path(@lesson_plan)
    end 
  end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def signup_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :grade)
  end

  def edit_params
      params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :name, :grade)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @books = GoogleBooks.search(params[:query])
    end 

    def new
    end 

    def create
    end 

    def show
    end 

    private

    def search_params
        params.require(:search).permit(:query)
    end 
end

app/controllers/subjects_controller.rb
  class SubjectsController < ApplicationController 

    def index
      @subjects = Subject.all.creation
    end 

    private

    def subject_params
      params.require(:subject).permit(:sub_name)
    end 
  end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_error.html.erb
<% if @book.errors.any? %>
  <div id="error-exp">
    <% @book.errors.full_messages.each do |msg|%>
      <li> <%= msg %> </li>
    <% end %>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @book.errors[:title].any? %>">
  <%= f.label :title, "Title: " %> <br>
  <%= f.text_field :title, class: 'input' %>
</div> <br>

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @book.errors[:author].any? %>">
  <%= f.label :author, "Author: " %> <br>
  <%= f.text_field :author, class: 'input' %>
</div> <br>

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @book.errors[:author].any? %>">
  <%= f.label :publisher, "Publisher: " %> <br>
  <%= f.text_field :publisher, class: 'input' %>
</div> <br>

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @book.errors[:author].any? %>">
  <%= f.label :pages, "Pages: " %> <br>
  <%= f.number_field :pages, class: 'input' %>
</div> <br>

 <!-- <div class="form-check">
    <%= f.label :subjects, "Subject(s): " %> <br>
    <%= f.collection_check_boxes :subject_ids, Subject.all, :id, :sub_name, class: 'checkbox' %>
  </div>  <br> -->

<%= f.submit class: 'btn' %>
<% end %>

app/views/books/_search.html.erb
<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">
<%= form_tag(books_path, method: :get) do %>
  <div class="form-group d-flex flex-wrap">
    <%= label_tag "Search By Title: " %>
    <%= text_field_tag(:search, params[:search], class: 'input') %> 
    <%= submit_tag "Search!", :title => nil, class: 'btn' %>
  </div>
<% end %>
</div>

app/views/books/edit.html.erb
<%= render 'error' %>

 <div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">

  <h1>Edit <%= @book.title %> </h1>

    <%= render 'form' %>

</div>

app/views/books/index.html.erb
  <%= render 'search' %>


<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">

  <% @books.each do |book| %>
    <li> <%= link_to "#{book.title} - #{book.author}", book_path(book), :class => 'link'  %> </li>
  <% end %>

</div>

app/views/books/new.html.erb
<%= render 'error' %>
 <div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">
<h3>Create Book: </h3>

  <%= render 'form' %>

 </div> 

app/views/books/show.html.erb
 <div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">
<h3>Title: <%= @book.title %></h3>
<h3>Author: <%= @book.author %></h3>
<h3>Publisher: <%= @book.publisher %></h3>
<h3>Pages: <%= @book.pages %></h3>
<p>Subject(s): 
  <% @book.subjects.each do |subject| %>
  <li> <%= subject.sub_name %> </li>
  <% end %>
</p> <br>

<%= link_to "Edit Book", edit_book_path(@book), :class => 'link'  %> | <%= link_to "Back To Library", books_path, :class => 'link'  %>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col">
    <div class="flex justify-content-center align-items-center content" style="background-color: rgba(210,194,179,0.83);border: 1px solid rgb(27,26,26);border-radius: 5px;padding: 5px;margin: 15px 15px 10px 10px;text-align: center;">
      <h3 style="font-family: Lora, serif;">Hello, <%= current_user.name %>!</h3> <br>

      <p> Add a <%= link_to "book", new_book_path, :class => 'link'  %> to the library.</p>
      <p> Create a new <%= link_to "lesson plan.", new_lesson_plan_path, :class => 'link'  %></p>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
    <div class="footer-basic" style="background-color: rgba(204,80,65,0.76);color: rgb(0,0,0);padding: 15px0px;border-top: 1px solid rgb(27,26,26) ;">
        <footer>
            <ul class="list-inline" style="color: rgb(255,255,255);">
                <li class="list-inline-item"><a href="http://arynnboniface.com">arynnboniface.com</a></li>
                <li class="list-inline-item"><a href="https://www.linkedin.com/in/arynn-boniface/">LinkedIn</a></li>
                <li class="list-inline-item"><a href="https://github.com/ronniekram">Github</a></li>
            </ul>
            <p class="copyright" style="color: rgb(255,255,255);height: 20px;font-size: 16px;">Arynn Boniface © 2020</p>
        </footer>
    </div>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-light navbar-expand-md" style="background-color: rgba(204,80,65,0.76);color: rgb(255,255,255);border-bottom: 1px solid rgb(27,26,26) ;">
        <div class="container-fluid"><a class="navbar-brand" href="#" style="color: rgba(255,255,255,0.9);font-family: Lora, serif;">Teacher's Library</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">

                <% if user_signed_in? %>
                  <ul class="nav navbar-nav">
                    <li class="nav-item" role="presentation"> <%= link_to 'School Library', books_path, :class => 'nav-link' %> </li>
                    <li class="nav-item" role="presentation"> <%= link_to 'My Lesson Plans', lesson_plans_path, :class => 'nav-link' %> </li>
                    <li class="nav-item" role="presentation"> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %> </li>
                    <li class="nav-item" role="presentation"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %> </li>
                </ul>

                <% else %>

                  <ul class="nav navbar-nav">
                    <li class="nav-item" role="presentation"> <%= link_to "Sign up", signup_path, :class => 'nav-link' %> </li>


                    <li class="nav-item" role="presentation"> <%= link_to "Login", login_path, :class => 'nav-link'  %> </li>

                  </ul>
                <% end %>
        </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teacher's Helper</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <link rel="stylesheet" href="../../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/Footer-Basic.css">
    <link rel="stylesheet" href="../../assets/css/styles.css"> -->
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'bootstrap.min' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>

    <div class="content">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </div>

    <%= render '/layouts/footer' %>
  </body>
</html>

app/views/lesson_plans/_error.html.erb
<% if @lesson_plan.errors.any? %>
  <div id="error-exp">
    <% @lesson_plan.errors.full_messages.each do |msg|%>
      <li> <%= msg %> </li>
    <% end %>
  </div>
<% end %>

app/views/lesson_plans/_form.html.erb
<%= form_with model: @lesson_plan, local: true do |f| %>

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @lesson_plan.errors[:name].any? %>">
  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %> <br>
</div>

  <div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @lesson_plan.errors[:subject].any? %>">
    <%= f.label "Subject: " %> <br>
    <%= collection_select(:lesson_plan, :subject_id, Subject.all, :id, :sub_name, prompt: true, class: "select") %> <br>
    </div>
  <div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @lesson_plan.errors[:subject].any? %>">
    <%= f.label "Create New: " %> <br>
    <%= f.fields_for :subject, @subject do |subject_fields| %>
      <%= subject_fields.text_field :sub_name %> <br>
    <% end %>
  </div>

  <div class="form-check">
    <%= f.label :books, "Book(s): " %> <br>
    <%= f.collection_check_boxes :book_ids, Book.all, :id, :title, class: 'checkbox' %>
  </div>  <br>


<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @lesson_plan.errors[:start_date].any? %>">
  <%= f.label :start_date, "Start Date: " %>
  <%= f.date_field :start_date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control', :style=> '1px solid rgb(27,26,26);' %> <br>
</div >

<div class="form-group d-flex flex-wrap<%= ' field_with_errors' if @lesson_plan.errors[:duration].any? %>">
  <%= f.label :duration, "Duration (in days): " %>
  <%= f.number_field :duration, :style=> '1px solid rgb(27,26,26);' %> <br>
</div >

  <%= f.submit class: 'btn' %>
<% end %>

app/views/lesson_plans/edit.html.erb
<%= render 'error' %>

<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">
  <h3>Edit Lesson Plan: </h3>

  <%= render 'form' %>

  <%= form_tag lesson_plan_path(@lesson_plan), :method => :delete, data: {confirm: "Are you sure?"} do %>
    <%= submit_tag "Delete Lesson Plan", class: 'btn' %>
  <% end %>

</div>

app/views/lesson_plans/index.html.erb
<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">

  <h3> <%= current_user.name %>'s Lesson Plans</h3>

  <% if current_user.lesson_plans.empty? %>
    <p> You don't have any lesson plans yet. <%= link_to "Add one?", new_lesson_plan_path, :class => 'link'  %></p>
  <% else %>
    <% current_user.lesson_plans.each do |plan| %>
      <li> <%= link_to "#{plan.name} - #{plan.lesson_start}", lesson_plan_path(plan), :class => 'link'  %></li>
    <% end %>
  <% end %>

</div>

app/views/lesson_plans/new.html.erb
<%= render 'error' %>

<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">
    <h3>New Lesson Plan: </h3>
    <%= render 'form' %>
</div>

app/views/lesson_plans/show.html.erb
<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">

  <h3><%= @lesson_plan.name %> </h3>

  <p>Start Date: <%= @lesson_plan.lesson_start %></p> <br>

  <p>Duration: <%= @lesson_plan.duration %> days</p> <br>

  <p>Subject: <%= @lesson_plan.subject.sub_name %> </p> <br>

  <p>Book(s): 
    <% @lesson_plan.books.each do |book| %>
      <li> <%= link_to "#{book.title} - #{book.author}", book_path(book), :class => 'link'  %> </li>
    <% end %>
  </p> <br>

  <%= link_to "Edit Lesson Plan", edit_lesson_plan_path(@lesson_plan), :class => 'link'  %>

</div>

app/views/search/index.html.erb
<div class="d-flex float-left flex-column justify-content-lg-start" style="background: rgba(210,194,179,0.83);border-radius: 10px;color: rgb(27,26,26);margin: 20px;padding: 20px;border: 1px solid rgb(27,26,26) ;">

    <form>
        <label>Search for a Book:</label> 
        <input type="text" id="search[query]" name="search_query" value="Search by title, author, publisher or subject" />
        <buton>Search</button>
    </form>
</div>

app/views/subjects/index.html.erb
<%= @subjects.each do |subject| %>
<li> <%= subject.sub_name %></li>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), :class => 'link'  %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), :class => 'link'  %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class => 'link'  %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), :class => 'link'  %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), :class => 'link'  %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), :class => 'link'  %><br />
  <% end %>
<% end %>